[package]
name = "libtiny_logger"
version = "0.1.0"
authors = ["Ömer Sinan Ağacan <omeragacan@gmail.com>"]
description = "Implements a logging UI for tiny"
edition = "2018"

[dependencies]
libtiny_common = { path = "../libtiny_common" }
log = "0.4"
time = "0.1"
